import type { SerializedStore } from '@/lib/data/store';
import type { IProduct } from '@/models/products';

export const STORES: SerializedStore = {
        _id: 'store_modern_tech',
        owner: 'demo_user',
        brandName: 'Future Gadgets',
        domain: 'future-gadgets',
        description: 'Future Gadgets is your premier destination for cutting-edge technology. We bring you the latest innovations that blend seamlessly into your life, enhancing both work and play.',
        themeId: 1,
        theme: { primaryColor: '#0891b2' },
        themeStructure: { header: true, hero: true, about: true, trust: true, productGrid: true, footer: true },
        headerLinks: [{ label: 'New Arrivals', href: '#' }, { label: 'Deals', href: '#' }, { label: 'Support', href: '#' }],
        hero: {
            title: 'Experience Tomorrow, Today.',
            subtitle: 'Cutting-edge technology that seamlessly blends into your life, enhancing both work and play.',
            imageUrl: 'https://picsum.photos/seed/tech_hero/1600/900',
        },
        about: {
            title: 'Pioneering Innovation',
            description: 'Founded in 2020, our mission is to make futuristic technology accessible to everyone. We meticulously curate and test every gadget to ensure it meets our high standards of quality and performance.',
        },
        footer: { text: 'All Rights Reserved.' },
        socialLinks: { facebook: '#', instagram: '#', tiktok: '#' },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    };

// Fake product data for theme previews
export const FAKE_PRODUCTS: IProduct[] = [
    {
        _id: 'product_1',
        owner: 'demo_user',
        name: 'Smart Watch Pro',
        slug: 'smart-watch-pro',
        description: 'Advanced smartwatch with health tracking, GPS, and long battery life. Perfect for fitness enthusiasts and tech lovers.',
        price: 249.99,
        discount: 10,
        stock: 50,
        category: 'Electronics & Gadgets',
        brand: 'TechBrand',
        mainImage: 'https://picsum.photos/seed/product1/800/800',
        images: [
            'https://picsum.photos/seed/product1-1/800/800',
            'https://picsum.photos/seed/product1-2/800/800',
        ],
        descriptionsImage: ['https://picsum.photos/seed/product1-desc1/800/800', 'https://picsum.photos/seed/product1-desc2/800/800'],
        sizes: ['Small', 'Medium', 'Large'],
        colors: ['Black', 'Silver', 'Rose Gold'],
        salesCount: 1250,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: 'product_2',
        owner: 'demo_user',
        name: 'Wireless Earbuds',
        slug: 'wireless-earbuds',
        description: 'Premium wireless earbuds with noise cancellation and crystal-clear sound quality. Up to 30 hours of battery life.',
        price: 129.99,
        stock: 75,
        category: 'Electronics & Gadgets',
        brand: 'AudioTech',
        mainImage: 'https://picsum.photos/seed/product2/800/800',
        images: [
            'https://picsum.photos/seed/product2-1/800/800',
        ],
        descriptionsImage: ['https://picsum.photos/seed/product2-desc1/800/800'],
        colors: ['Black', 'White'],
        salesCount: 890,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: 'product_3',
        owner: 'demo_user',
        name: 'Tablet Pro 12"',
        slug: 'tablet-pro-12',
        description: 'High-performance tablet with stunning display and powerful processor. Ideal for work and entertainment.',
        price: 599.99,
        discount: 15,
        stock: 30,
        category: 'Electronics & Gadgets',
        brand: 'TechBrand',
        mainImage: 'https://picsum.photos/seed/product3/800/800',
        images: [
            'https://picsum.photos/seed/product3-1/800/800',
            'https://picsum.photos/seed/product3-2/800/800',
        ],
        descriptionsImage: ['https://picsum.photos/seed/product3-desc1/800/800', 'https://picsum.photos/seed/product3-desc2/800/800'],
        sizes: ['64GB', '128GB', '256GB'],
        colors: ['Space Gray', 'Silver'],
        bundles: {
            type: 'buy_x_get_y',
            buyQuantity: 2,
            getQuantity: 1,
            enabled: true,
        },
        salesCount: 450,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: 'product_4',
        owner: 'demo_user',
        name: 'Smartphone X',
        slug: 'smartphone-x',
        description: 'Latest flagship smartphone with advanced camera system and lightning-fast performance.',
        price: 899.99,
        stock: 40,
        category: 'Electronics & Gadgets',
        brand: 'TechBrand',
        mainImage: 'https://picsum.photos/seed/product4/800/800',
        images: [
            'https://picsum.photos/seed/product4-1/800/800',
        ],
        descriptionsImage: ['https://picsum.photos/seed/product4-desc1/800/800'],
        sizes: ['128GB', '256GB', '512GB'],
        colors: ['Midnight', 'Starlight', 'Blue'],
        salesCount: 2100,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: 'product_5',
        owner: 'demo_user',
        name: 'Laptop Ultra',
        slug: 'laptop-ultra',
        description: 'Sleek and powerful laptop perfect for professionals. Ultra-thin design with all-day battery life.',
        price: 1299.99,
        discount: 20,
        stock: 25,
        category: 'Electronics & Gadgets',
        brand: 'TechBrand',
        mainImage: 'https://picsum.photos/seed/product5/800/800',
        images: [
            'https://picsum.photos/seed/product5-1/800/800',
            'https://picsum.photos/seed/product5-2/800/800',
        ],
        descriptionsImage: ['https://picsum.photos/seed/product5-desc1/800/800', 'https://picsum.photos/seed/product5-desc2/800/800'],
        sizes: ['512GB', '1TB'],
        colors: ['Space Gray', 'Silver'],
        bundles: {
            type: 'percentage_off',
            percentageOff: 15,
            enabled: true,
        },
        salesCount: 680,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: 'product_6',
        owner: 'demo_user',
        name: 'Gaming Headset',
        slug: 'gaming-headset',
        description: 'Professional gaming headset with 7.1 surround sound and RGB lighting. Comfortable for long gaming sessions.',
        price: 149.99,
        stock: 60,
        category: 'Electronics & Gadgets',
        brand: 'GameTech',
        mainImage: 'https://picsum.photos/seed/product6/800/800',
        images: [
            'https://picsum.photos/seed/product6-1/800/800',
        ],
        descriptionsImage: ['https://picsum.photos/seed/product6-desc1/800/800'],
        colors: ['Black', 'White', 'Red'],
        salesCount: 520,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        _id: 'product_preview_demo',
        owner: 'demo_user',
        name: 'Premium Smart Watch Ultra',
        slug: 'premium-smart-watch-ultra',
        description: 'The ultimate smartwatch experience with advanced health monitoring, GPS tracking, and premium materials. Features a stunning AMOLED display, water resistance up to 50m, and battery life that lasts up to 7 days. Perfect for fitness enthusiasts and professionals who demand the best.',
        price: 399.99,
        discount: 20,
        stock: 45,
        category: 'Electronics & Gadgets',
        brand: 'TechBrand',
        mainImage: 'https://picsum.photos/seed/preview-watch-main/800/800',
        images: [
            'https://picsum.photos/seed/preview-watch-1/800/800',
            'https://picsum.photos/seed/preview-watch-2/800/800',
            'https://picsum.photos/seed/preview-watch-3/800/800',
            'https://picsum.photos/seed/preview-watch-4/800/800',
        ],
        descriptionsImage: [
            'https://picsum.photos/seed/preview-watch-desc1/800/800',
            'https://picsum.photos/seed/preview-watch-desc2/800/800',
            'https://picsum.photos/seed/preview-watch-desc3/800/800',
            'https://picsum.photos/seed/preview-watch-desc4/800/800',
        ],
        sizes: ['40mm', '44mm'],
        colors: ['Titanium Black', 'Stainless Steel Silver', 'Rose Gold'],
        bundles: {
            type: 'buy_x_get_y',
            buyQuantity: 2,
            getQuantity: 1,
            enabled: true,
        },
        salesCount: 1850,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];