
export const storeThemes = [
    // 1. Classic Green
    {
        name: "Classic Green",
        theme: {
        primaryColor: "#22c55e",
        secondaryColor: "#16a34a",
        backgroundColor: "#f0fdf4",
        textColor: "#1a1a1a",
        buttonColor: "#22c55e",
        headerColor: "#d1fae5",
        footerColor: "#064e3b",
        borderColor: "#16a34a",
        gradient: { from: "#22c55e", via: "#4ade80", to: "#16a34a" },
        borderRadius: "0.5rem",
        shadow: true,
        fontFamily: "Inter",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 2. Modern Blue
    {
        name: "Modern Blue",
        theme: {
        primaryColor: "#3b82f6",
        secondaryColor: "#2563eb",
        backgroundColor: "#f0f6ff",
        textColor: "#111827",
        buttonColor: "#3b82f6",
        headerColor: "#dbeafe",
        footerColor: "#1e3a8a",
        borderColor: "#2563eb",
        gradient: { from: "#60a5fa", via: "#3b82f6", to: "#2563eb" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Poppins",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 3. Luxury Black & Gold
    {
        name: "Luxury Black & Gold",
        theme: {
        primaryColor: "#eab308",
        secondaryColor: "#ca8a04",
        backgroundColor: "#fafafa",
        textColor: "#111111",
        buttonColor: "#eab308",
        headerColor: "#fef3c7",
        footerColor: "#111111",
        borderColor: "#ca8a04",
        gradient: { from: "#facc15", via: "#fcd34d", to: "#ca8a04" },
        borderRadius: "0.5rem",
        shadow: true,
        fontFamily: "Playfair Display",
        headingWeight: "800",
        buttonStyle: "solid",
        },
    },
    // 4. Soft Purple
    {
        name: "Soft Purple",
        theme: {
        primaryColor: "#8b5cf6",
        secondaryColor: "#7c3aed",
        backgroundColor: "#f5f3ff",
        textColor: "#2e1065",
        buttonColor: "#8b5cf6",
        headerColor: "#ede9fe",
        footerColor: "#4c1d95",
        borderColor: "#7c3aed",
        gradient: { from: "#c4b5fd", via: "#a78bfa", to: "#7c3aed" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Nunito",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 5. Sunset Coral
    {
        name: "Sunset Coral",
        theme: {
        primaryColor: "#f97316",
        secondaryColor: "#ea580c",
        backgroundColor: "#fff7ed",
        textColor: "#1f2937",
        buttonColor: "#f97316",
        headerColor: "#ffedd5",
        footerColor: "#7c2d12",
        borderColor: "#ea580c",
        gradient: { from: "#fdba74", via: "#fb923c", to: "#ea580c" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Quicksand",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 6. Minimal Gray
    {
        name: "Minimal Gray",
        theme: {
        primaryColor: "#4b5563",
        secondaryColor: "#374151",
        backgroundColor: "#f9fafb",
        textColor: "#111827",
        buttonColor: "#4b5563",
        headerColor: "#e5e7eb",
        footerColor: "#111827",
        borderColor: "#6b7280",
        gradient: { from: "#6b7280", via: "#9ca3af", to: "#374151" },
        borderRadius: "0.5rem",
        shadow: false,
        fontFamily: "Inter",
        headingWeight: "600",
        buttonStyle: "outline",
        },
    },
    // 7. Ocean Teal
    {
        name: "Ocean Teal",
        theme: {
        primaryColor: "#14b8a6",
        secondaryColor: "#0d9488",
        backgroundColor: "#f0fdfa",
        textColor: "#0f172a",
        buttonColor: "#14b8a6",
        headerColor: "#ccfbf1",
        footerColor: "#115e59",
        borderColor: "#0d9488",
        gradient: { from: "#5eead4", via: "#2dd4bf", to: "#0d9488" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Rubik",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 8. Rose Blush
    {
        name: "Rose Blush",
        theme: {
        primaryColor: "#f43f5e",
        secondaryColor: "#be123c",
        backgroundColor: "#fff1f2",
        textColor: "#1f2937",
        buttonColor: "#f43f5e",
        headerColor: "#ffe4e6",
        footerColor: "#881337",
        borderColor: "#be123c",
        gradient: { from: "#fb7185", via: "#f472b6", to: "#be123c" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Lato",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 9. Emerald Forest
    {
        name: "Emerald Forest",
        theme: {
        primaryColor: "#10b981",
        secondaryColor: "#047857",
        backgroundColor: "#ecfdf5",
        textColor: "#064e3b",
        buttonColor: "#10b981",
        headerColor: "#d1fae5",
        footerColor: "#064e3b",
        borderColor: "#047857",
        gradient: { from: "#34d399", via: "#22c55e", to: "#047857" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Montserrat",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 10. Arctic White
    {
        name: "Arctic White",
        theme: {
        primaryColor: "#0ea5e9",
        secondaryColor: "#0369a1",
        backgroundColor: "#f8fafc",
        textColor: "#0f172a",
        buttonColor: "#0ea5e9",
        headerColor: "#e0f2fe",
        footerColor: "#0c4a6e",
        borderColor: "#0369a1",
        gradient: { from: "#38bdf8", via: "#7dd3fc", to: "#0369a1" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Inter",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 11. Midnight Indigo
    {
        name: "Midnight Indigo",
        theme: {
        primaryColor: "#4338ca",
        secondaryColor: "#312e81",
        backgroundColor: "#eef2ff",
        textColor: "#1e1b4b",
        buttonColor: "#4338ca",
        headerColor: "#c7d2fe",
        footerColor: "#1e1b4b",
        borderColor: "#312e81",
        gradient: { from: "#6366f1", via: "#818cf8", to: "#312e81" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Poppins",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 12. Cyber Neon
    {
        name: "Cyber Neon",
        theme: {
        primaryColor: "#06b6d4",
        secondaryColor: "#0ea5e9",
        backgroundColor: "#0f172a",
        textColor: "#f8fafc",
        buttonColor: "#06b6d4",
        headerColor: "#1e293b",
        footerColor: "#020617",
        borderColor: "#0ea5e9",
        gradient: { from: "#22d3ee", via: "#06b6d4", to: "#0ea5e9" },
        borderRadius: "0.5rem",
        shadow: true,
        fontFamily: "Space Grotesk",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 13. Desert Sand
    {
        name: "Desert Sand",
        theme: {
        primaryColor: "#f59e0b",
        secondaryColor: "#b45309",
        backgroundColor: "#fff7ed",
        textColor: "#78350f",
        buttonColor: "#f59e0b",
        headerColor: "#ffedd5",
        footerColor: "#7c2d12",
        borderColor: "#b45309",
        gradient: { from: "#fbbf24", via: "#fcd34d", to: "#b45309" },
        borderRadius: "0.5rem",
        shadow: true,
        fontFamily: "Karla",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 14. Frost Mint
    {
        name: "Frost Mint",
        theme: {
        primaryColor: "#34d399",
        secondaryColor: "#059669",
        backgroundColor: "#ecfdf5",
        textColor: "#065f46",
        buttonColor: "#34d399",
        headerColor: "#d1fae5",
        footerColor: "#064e3b",
        borderColor: "#059669",
        gradient: { from: "#6ee7b7", via: "#34d399", to: "#059669" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Inter",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 15. Lavender Dream
    {
        name: "Lavender Dream",
        theme: {
        primaryColor: "#a78bfa",
        secondaryColor: "#7c3aed",
        backgroundColor: "#f5f3ff",
        textColor: "#312e81",
        buttonColor: "#a78bfa",
        headerColor: "#ede9fe",
        footerColor: "#4c1d95",
        borderColor: "#7c3aed",
        gradient: { from: "#c4b5fd", via: "#a78bfa", to: "#7c3aed" },
        borderRadius: "0.75rem",
        shadow: true,
        fontFamily: "Nunito",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    // 16. Graphite Dark
    {
        name: "Graphite Dark",
        theme: {
        primaryColor: "#6b7280",
        secondaryColor: "#374151",
        backgroundColor: "#1f2937",
        textColor: "#f3f4f6",
        buttonColor: "#9ca3af",
        headerColor: "#111827",
        footerColor: "#030712",
        borderColor: "#374151",
        gradient: { from: "#9ca3af", via: "#6b7280", to: "#374151" },
        borderRadius: "0.5rem",
        shadow: true,
        fontFamily: "Roboto",
        headingWeight: "700",
        buttonStyle: "solid",
        },
    },
    ];
